export const categories = [
  { id: '1', name: 'Cameras & Gear', icon: 'Camera' },
  { id: '2', name: 'Drones', icon: 'Plane' },
  { id: '3', name: 'Audio Equipment', icon: 'Headphones' },
  { id: '4', name: 'Gaming Consoles', icon: 'Gamepad2' },
  { id: '5', name: 'Power Tools', icon: 'Wrench' },
  { id: '6', name: 'Camping Gear', icon: 'Tent' },
];

export const mockItems = [
  {
    id: 'item-1',
    ownerId: 'user-2',
    title: 'Sony A7III Mirrorless Camera with 28-70mm Lens',
    description: 'Perfect for professional photography and videography. Includes 2 batteries, a 64GB SD card, and a carrying case.',
    dailyRate: 45,
    securityDeposit: 300,
    category: 'Cameras & Gear',
    condition: 'Excellent',
    city: 'San Francisco',
    state: 'CA',
    status: 'ACTIVE',
    rating: 4.9,
    reviewsCount: 24,
    images: [
      'https://images.unsplash.com/photo-1516724562728-afc824a36e84?q=80&w=2071&auto=format&fit=crop',
    ],
  },
  {
    id: 'item-2',
    ownerId: 'user-3',
    title: 'DJI Mavic 3 Pro Drone',
    description: 'Capture stunning aerial footage with this professional drone. Features Hasselblad camera, 43-min flight time, and omnidirectional obstacle sensing.',
    dailyRate: 85,
    securityDeposit: 800,
    category: 'Drones',
    condition: 'Like New',
    city: 'New York',
    state: 'NY',
    status: 'ACTIVE',
    rating: 5.0,
    reviewsCount: 12,
    images: [
      'https://images.unsplash.com/photo-1579829366248-204fe8413f31?q=80&w=2070&auto=format&fit=crop',
    ],
  },
  {
    id: 'item-3',
    ownerId: 'user-4',
    title: 'PlayStation 5 Console with 2 Controllers',
    description: 'Next-gen gaming experience. Comes with two DualSense controllers and 3 popular games pre-installed.',
    dailyRate: 25,
    securityDeposit: 200,
    category: 'Gaming Consoles',
    condition: 'Good',
    city: 'Austin',
    state: 'TX',
    status: 'ACTIVE',
    rating: 4.7,
    reviewsCount: 38,
    images: [
      'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?q=80&w=2074&auto=format&fit=crop',
    ],
  },
  {
    id: 'item-4',
    ownerId: 'user-5',
    title: 'Bose S1 Pro Portable Bluetooth PA System',
    description: 'High-quality sound for small parties and events. Battery lasts up to 11 hours. Built-in mixer with EQ.',
    dailyRate: 35,
    securityDeposit: 150,
    category: 'Audio Equipment',
    condition: 'Excellent',
    city: 'Seattle',
    state: 'WA',
    status: 'ACTIVE',
    rating: 4.8,
    reviewsCount: 19,
    images: [
      'https://images.unsplash.com/photo-1545127398-14699f92334b?q=80&w=1964&auto=format&fit=crop',
    ],
  },
];
